### ISSUE TITLE
ignore dealer down card (wrt count) for playing decisions

### ISSUE THREAD

**Issue by voltij** [Gamah/bjsim-cpp#3]
ignore the dealer down card for playing decisions during the hand

**Comment by voltij** [comment]
ha ha ha

**Comment by Gamah** [comment]
we aren't closing this until i figure out how to rewrite history to attribute it to the commits where i fixed it....

**Comment by Gamah** [comment]
I never figured out how to attribute this issue in that comment so closing now.
